name: CI
on: [push, pull_request]
jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: denolib/setup-deno@v2
    with:
      deno-version: v1.5
    - run: deno test -A --importmap=import_map.json --config=tsconfig.json --unstable ./test/css
      env:
        CI: true
